### PR TITLE
On click again an opened subitem close the menu

### PR DESCRIPTION
**Pull request by Mte90**

### CODE REVIEW

**Comment by Mte90** [comment]
This code as it is doens't work if there are opened 2 sub menu.

**Comment by Mte90** [comment]
The issue happens because the element got focus, so if the other one has focus and you click the other one works badly. But happens on desktop emulating mobile so is not a big issue.

**Comment by Mte90** [comment]
also for this?

**Comment by francgrasso** [comment]
Hello there, I have elaborated a little different version of your idea. I'm checking all menu items siblings to assure they are not opened. Please check commit 93d8d0e and let me know if this is what you need.
At this link you can find a small video about current behaviour: https://www.loom.com/share/9f46111b6bfb46e4bb6ece3e9d5725ce

**Comment by Mte90** [comment]
Seems good but I don't know what happens if you click on a sub menu of about like About proteo in the screencast.

**Comment by francgrasso** [comment]
here: https://www.loom.com/share/a8fa89f8334f44f9aaa8719acfa05834

**Comment by Mte90** [comment]
Perfect!
Also my pr had some code optimization to save some bytes (so google is happy) like in https://github.com/yithemes/yith-proteo/pull/30/files#diff-9f4bb529f4004b98912e8a46a6e0dbeb49f6462b2466989e5f11318e7de5e876L68-L73 line 68/73

**Comment by francgrasso** [comment]
sorry but this is not related to the issue of this pull request. Please open a new one with the updated code.
I'm closing it now. Thanks for your time :)

**Pull request closed without merging**
